// <auto-generated />
namespace HospitalsTestsAndVaccines.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProbablyTheLastOne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProbablyTheLastOne));
        
        string IMigrationMetadata.Id
        {
            get { return "202101241129175_ProbablyTheLastOne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
